# Generated by Django 5.2.7 on 2025-11-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'compras',
                'managed': False,
            },
        ),
    ]
